### ISSUE TITLE
Example `standalone` fails

### ISSUE THREAD

**Issue by hannemariavister** [hannemariavister/terraform-nomad-nifiregistry#30]
## Current behaviour
By executing the example `example/standalone` with command `make up-standalone` following error message occurs:
```
TASK [Terraform nifi_registry standalone] **************************************
fatal: [default]: FAILED! => {
    "changed": false
}

MSG:

Failed to validate Terraform configuration files:

Error: Unsupported argument

  on main.tf line 7, in module "nifi_registry":
   7:   nomad_host_volume = "persistence"

An argument named "nomad_host_volume" is not expected here.


Error: Unsupported argument

  on main.tf line 15, in module "nifi_registry":
  15:   use_host_volume = false

An argument named "use_host_volume" is not expected here.



PLAY RECAP *********************************************************************
default                    : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

```

## How to reproduce?
Run `make up-standalone` 

## Suggestion(s)/solution(s) [Optional]
Remove variables:
- `nomad_host_volume` from [main.tf](https://github.com/hannemariavister/terraform-nomad-nifiregistry/blob/master/example/standalone/main.tf#L7)
- `use_host_volume` from [main.tf](https://github.com/hannemariavister/terraform-nomad-nifiregistry/blob/master/example/standalone/main.tf#L15)

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [x] Added to milestone

**Comment by karimacherradi** [comment]
Solved in isuue_22
