### ISSUE TITLE
Saving versioned flows to the git repository

### ISSUE THREAD

**Issue by karimacherradi** [hannemariavister/terraform-nomad-nifiregistry#5]
## Feature description
Configure GitFlowPersistenceProvider in NiFi Registry so that versioned flows in NiFi are automatically saved to a Git repository. 
https://community.cloudera.com/t5/Community-Articles/Storing-Apache-NiFi-Versioned-Flows-in-a-Git-Repository/ta-p/248713
## Definition of done
Versioned flows in NiFi are automatically saved to a Git repository.
 
## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [x] Added to milestone

**Comment by hannemariavister** [comment]
Related to issue #14.
